### ISSUE TITLE
Improvement suggestions 

### ISSUE THREAD

**Issue by SirYaro** [prikhodkop/kdm_story_app#68]
1. search should be able to find terms using both English and translated phrases not just one. Ex. If I'm on PL version I'm unable to find "sword", only "miecz" works. Desirable solution would be if both phrases find the entry and display text in language chosen in configuration. (or both but that should be configurable option)

![obraz](https://user-images.githubusercontent.com/5879723/89732712-f15f1280-da50-11ea-957a-b49e37f5745a.png)
![obraz](https://user-images.githubusercontent.com/5879723/89732734-10f63b00-da51-11ea-9b31-ec3c5d5c1c12.png)

2. Button "random" had to clear text box prior to sending text there. If there was any text there before in will interfere with the whole functionality. Example below. "losow" it's a polish "random" equivalent.
![obraz](https://user-images.githubusercontent.com/5879723/89732868-d80a9600-da51-11ea-9fcc-15e313925f54.png)

3. Add random terrain to the random draw list.
![obraz](https://user-images.githubusercontent.com/5879723/89732893-025c5380-da52-11ea-96ce-0787c38fe93a.png)

**Comment by prikhodkop** [comment]
1. Done. Now both eng version and translation are shown. And you may serach with both.
2. Good idea. Done.
3. That one is a bit tricky :/ Because, unlike other randow draws in game this one depends on which monster you fight. As you need to place some cards from the deck before random draw. And unlike with fighting arts and disorders reference window interface is just not fit for the task. Eventually i would need to add draw resource button to showdown event itself.

**Comment by prikhodkop** [comment]
So, i guess i would just close the current one and open another issue, that asks to add resource draw to showdown directly (this way i would also be able to make it work like howevable tooltip to allow, to quickly check terrain cards.
